#!/usr/bin/env python
# -*- coding: utf-8 -*-

import unittest

from ParseHeader1Test import ParseHeader1Test
from ParseHeader2Test import ParseHeader2Test
from ParseHeader3Test import ParseHeader3Test
from ParseRawContentTest import ParseRawContentTest
from ParseArticleReferenceTest import ParseArticleReferenceTest
from ParseEditTest import ParseEditTest
from ParseWordReferenceTest import ParseWordReferenceTest
from ParseAlineaReferenceTest import ParseAlineaReferenceTest
from ParseAlineaDefinitionTest import ParseAlineaDefinitionTest
from ParseHeader2ReferenceTest import ParseHeader2ReferenceTest
from ParseHeader2DefinitionTest import ParseHeader2DefinitionTest
from ParseCodeReferenceTest import ParseCodeReferenceTest
from ParseLawReferenceTest import ParseLawReferenceTest
from ParseMultiplicativeAdverbTest import ParseMultiplicativeAdverbTest
from ParseSentenceDefinitionTest import ParseSentenceDefinitionTest
from ParseSentenceReferenceTest import ParseSentenceReferenceTest
from ParseWordDefinitionTest import ParseWordDefinitionTest
from ParseArticleDefinitionTest import ParseArticleDefinitionTest
from ParseMentionDefinitionTest import ParseMentionDefinitionTest
from ParseHeader1DefinitionTest import ParseHeader1DefinitionTest
from ParseDefinitionListTest import ParseDefinitionListTest
from ParseHeader3DefinitionTest import ParseHeader3DefinitionTest
from ParseHeader3ReferenceTest import ParseHeader3ReferenceTest
from ParseSectionReferenceTest import ParseSectionReferenceTest
from ParseSubSectionReferenceTest import ParseSubSectionReferenceTest
from ParseChapterReferenceTest import ParseChapterReferenceTest
from ParseParagraphReferenceTest import ParseParagraphReferenceTest
from ParseSubParagraphDefinitionTest import ParseSubParagraphDefinitionTest
from ParseCodePartReferenceTest import ParseCodePartReferenceTest
from ParseTitleReferenceTest import ParseTitleReferenceTest
from ParseBookReferenceTest import ParseBookReferenceTest
from ResolveFullyQualifiedReferencesVisitorTest import ResolveFullyQualifiedReferencesVisitorTest
from SortReferencesVisitorTest import SortReferencesVisitorTest
from ForkReferenceVisitorTest import ForkReferenceVisitorTest
from ForkEditVisitorTest import ForkEditVisitorTest

if __name__ == '__main__':
    unittest.main()
