#!/usr/bin/env python
# -*- coding: utf-8 -*-

import unittest

from ParseBillHeader1Test import ParseBillHeader1Test
from ParseBillHeader2Test import ParseBillHeader2Test
from ParseBillHeader3Test import ParseBillHeader3Test
from ParseRawContentTest import ParseRawContentTest
from ParseArticleReferenceTest import ParseArticleReferenceTest
from ParseEditTest import ParseEditTest
from ParseWordsReferenceTest import ParseWordsReferenceTest
from ParseAlineaReferenceTest import ParseAlineaReferenceTest
from ParseAlineaDefinitionTest import ParseAlineaDefinitionTest
from ParseHeader2ReferenceTest import ParseHeader2ReferenceTest
from ParseHeader2DefinitionTest import ParseHeader2DefinitionTest
from ParseCodeReferenceTest import ParseCodeReferenceTest
from ParseLawReferenceTest import ParseLawReferenceTest
from ParseMultiplicativeAdverbTest import ParseMultiplicativeAdverbTest
from ParseSentenceDefinitionTest import ParseSentenceDefinitionTest
from ParseSentenceReferenceTest import ParseSentenceReferenceTest
from ParseWordsDefinitionTest import ParseWordsDefinitionTest
from ParseArticleDefinitionTest import ParseArticleDefinitionTest
from ParseMentionDefinitionTest import ParseMentionDefinitionTest
from ParseHeader1DefinitionTest import ParseHeader1DefinitionTest
from ParseDefinitionListTest import ParseDefinitionListTest
from ParseHeader3DefinitionTest import ParseHeader3DefinitionTest
from ParseHeader3ReferenceTest import ParseHeader3ReferenceTest
from ParseSectionReferenceTest import ParseSectionReferenceTest
from ParseSubSectionReferenceTest import ParseSubSectionReferenceTest
from ParseChapterReferenceTest import ParseChapterReferenceTest
from ParseTitleReferenceTest import ParseTitleReferenceTest
from ResolveFullyQualifiedReferencesVisitorTest import ResolveFullyQualifiedReferencesVisitorTest
from SortReferencesVisitorTest import SortReferencesVisitorTest
from ForkReferenceVisitorTest import ForkReferenceVisitorTest
from ForkEditVisitorTest import ForkEditVisitorTest

if __name__ == '__main__':
    unittest.main()
