#!/usr/bin/env python
# -*- coding: utf-8 -*-

import unittest

from ParseArticleHeader1Test import ParseArticleHeader1Test
from ParseArticleReferenceTest import ParseArticleReferenceTest
from ParseEditTest import ParseEditTest
from ParseAlineaReferenceTest import ParseAlineaReferenceTest
from ParseAlineaDefinitionTest import ParseAlineaDefinitionTest
from ParseHeader2ReferenceTest import ParseHeader2ReferenceTest
from ParseHeader2DefinitionTest import ParseHeader2DefinitionTest
from ParseCodeReferenceTest import ParseCodeReferenceTest
from ParseLawReferenceTest import ParseLawReferenceTest
from ParseMultiplicativeAdverbTest import ParseMultiplicativeAdverbTest
from ParseSentenceDefinitionTest import ParseSentenceDefinitionTest
from ParseWordsDefinitionTest import ParseWordsDefinitionTest
from ParseArticleDefinitionTest import ParseArticleDefinitionTest
from ParseMentionDefinitionTest import ParseMentionDefinitionTest
from ParseHeader1DefinitionTest import ParseHeader1DefinitionTest
from ParseDefinitionListTest import ParseDefinitionListTest
from ResolveFullyQualifiedReferencesVisitorTest import ResolveFullyQualifiedReferencesVisitorTest
from SortReferencesVisitorTest import SortReferencesVisitorTest

if __name__ == '__main__':
    unittest.main()
